/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminSetupRouteImport } from './routes/admin-setup'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated/wallet'
import { Route as AuthenticatedTradeRouteImport } from './routes/_authenticated/trade'
import { Route as AuthenticatedScannerRouteImport } from './routes/_authenticated/scanner'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPredictRouteImport } from './routes/_authenticated/predict'
import { Route as AuthenticatedPositionsRouteImport } from './routes/_authenticated/positions'
import { Route as AuthenticatedForexRouteImport } from './routes/_authenticated/forex'
import { Route as AuthenticatedCryptoRouteImport } from './routes/_authenticated/crypto'
import { Route as AuthenticatedBotBuilderRouteImport } from './routes/_authenticated/bot-builder'
import { Route as AuthenticatedBinaryRouteImport } from './routes/_authenticated/binary'
import { Route as AuthenticatedAviatorRouteImport } from './routes/_authenticated/aviator'
import { Route as AuthenticatedAppsRouteImport } from './routes/_authenticated/apps'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiDarajaStkCallbackRouteImport } from './routes/api/daraja/stk-callback'
import { Route as ApiDarajaB2cTimeoutRouteImport } from './routes/api/daraja/b2c-timeout'
import { Route as ApiDarajaB2cResultRouteImport } from './routes/api/daraja/b2c-result'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSetupRoute = AdminSetupRouteImport.update({
  id: '/admin-setup',
  path: '/admin-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTradeRoute = AuthenticatedTradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScannerRoute = AuthenticatedScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPredictRoute = AuthenticatedPredictRouteImport.update({
  id: '/predict',
  path: '/predict',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPositionsRoute = AuthenticatedPositionsRouteImport.update({
  id: '/positions',
  path: '/positions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedForexRoute = AuthenticatedForexRouteImport.update({
  id: '/forex',
  path: '/forex',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCryptoRoute = AuthenticatedCryptoRouteImport.update({
  id: '/crypto',
  path: '/crypto',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBotBuilderRoute = AuthenticatedBotBuilderRouteImport.update({
  id: '/bot-builder',
  path: '/bot-builder',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBinaryRoute = AuthenticatedBinaryRouteImport.update({
  id: '/binary',
  path: '/binary',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAviatorRoute = AuthenticatedAviatorRouteImport.update({
  id: '/aviator',
  path: '/aviator',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppsRoute = AuthenticatedAppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiDarajaStkCallbackRoute = ApiDarajaStkCallbackRouteImport.update({
  id: '/api/daraja/stk-callback',
  path: '/api/daraja/stk-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDarajaB2cTimeoutRoute = ApiDarajaB2cTimeoutRouteImport.update({
  id: '/api/daraja/b2c-timeout',
  path: '/api/daraja/b2c-timeout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDarajaB2cResultRoute = ApiDarajaB2cResultRouteImport.update({
  id: '/api/daraja/b2c-result',
  path: '/api/daraja/b2c-result',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-setup': typeof AdminSetupRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/apps': typeof AuthenticatedAppsRoute
  '/aviator': typeof AuthenticatedAviatorRoute
  '/binary': typeof AuthenticatedBinaryRoute
  '/bot-builder': typeof AuthenticatedBotBuilderRoute
  '/crypto': typeof AuthenticatedCryptoRoute
  '/forex': typeof AuthenticatedForexRoute
  '/positions': typeof AuthenticatedPositionsRoute
  '/predict': typeof AuthenticatedPredictRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/scanner': typeof AuthenticatedScannerRoute
  '/trade': typeof AuthenticatedTradeRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/api/daraja/b2c-result': typeof ApiDarajaB2cResultRoute
  '/api/daraja/b2c-timeout': typeof ApiDarajaB2cTimeoutRoute
  '/api/daraja/stk-callback': typeof ApiDarajaStkCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-setup': typeof AdminSetupRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/apps': typeof AuthenticatedAppsRoute
  '/aviator': typeof AuthenticatedAviatorRoute
  '/binary': typeof AuthenticatedBinaryRoute
  '/bot-builder': typeof AuthenticatedBotBuilderRoute
  '/crypto': typeof AuthenticatedCryptoRoute
  '/forex': typeof AuthenticatedForexRoute
  '/positions': typeof AuthenticatedPositionsRoute
  '/predict': typeof AuthenticatedPredictRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/scanner': typeof AuthenticatedScannerRoute
  '/trade': typeof AuthenticatedTradeRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/api/daraja/b2c-result': typeof ApiDarajaB2cResultRoute
  '/api/daraja/b2c-timeout': typeof ApiDarajaB2cTimeoutRoute
  '/api/daraja/stk-callback': typeof ApiDarajaStkCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin-setup': typeof AdminSetupRoute
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/apps': typeof AuthenticatedAppsRoute
  '/_authenticated/aviator': typeof AuthenticatedAviatorRoute
  '/_authenticated/binary': typeof AuthenticatedBinaryRoute
  '/_authenticated/bot-builder': typeof AuthenticatedBotBuilderRoute
  '/_authenticated/crypto': typeof AuthenticatedCryptoRoute
  '/_authenticated/forex': typeof AuthenticatedForexRoute
  '/_authenticated/positions': typeof AuthenticatedPositionsRoute
  '/_authenticated/predict': typeof AuthenticatedPredictRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/scanner': typeof AuthenticatedScannerRoute
  '/_authenticated/trade': typeof AuthenticatedTradeRoute
  '/_authenticated/wallet': typeof AuthenticatedWalletRoute
  '/api/daraja/b2c-result': typeof ApiDarajaB2cResultRoute
  '/api/daraja/b2c-timeout': typeof ApiDarajaB2cTimeoutRoute
  '/api/daraja/stk-callback': typeof ApiDarajaStkCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-setup'
    | '/auth'
    | '/admin'
    | '/apps'
    | '/aviator'
    | '/binary'
    | '/bot-builder'
    | '/crypto'
    | '/forex'
    | '/positions'
    | '/predict'
    | '/profile'
    | '/scanner'
    | '/trade'
    | '/wallet'
    | '/api/daraja/b2c-result'
    | '/api/daraja/b2c-timeout'
    | '/api/daraja/stk-callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-setup'
    | '/auth'
    | '/admin'
    | '/apps'
    | '/aviator'
    | '/binary'
    | '/bot-builder'
    | '/crypto'
    | '/forex'
    | '/positions'
    | '/predict'
    | '/profile'
    | '/scanner'
    | '/trade'
    | '/wallet'
    | '/api/daraja/b2c-result'
    | '/api/daraja/b2c-timeout'
    | '/api/daraja/stk-callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin-setup'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/apps'
    | '/_authenticated/aviator'
    | '/_authenticated/binary'
    | '/_authenticated/bot-builder'
    | '/_authenticated/crypto'
    | '/_authenticated/forex'
    | '/_authenticated/positions'
    | '/_authenticated/predict'
    | '/_authenticated/profile'
    | '/_authenticated/scanner'
    | '/_authenticated/trade'
    | '/_authenticated/wallet'
    | '/api/daraja/b2c-result'
    | '/api/daraja/b2c-timeout'
    | '/api/daraja/stk-callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminSetupRoute: typeof AdminSetupRoute
  AuthRoute: typeof AuthRoute
  ApiDarajaB2cResultRoute: typeof ApiDarajaB2cResultRoute
  ApiDarajaB2cTimeoutRoute: typeof ApiDarajaB2cTimeoutRoute
  ApiDarajaStkCallbackRoute: typeof ApiDarajaStkCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-setup': {
      id: '/admin-setup'
      path: '/admin-setup'
      fullPath: '/admin-setup'
      preLoaderRoute: typeof AdminSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trade': {
      id: '/_authenticated/trade'
      path: '/trade'
      fullPath: '/trade'
      preLoaderRoute: typeof AuthenticatedTradeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scanner': {
      id: '/_authenticated/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof AuthenticatedScannerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/predict': {
      id: '/_authenticated/predict'
      path: '/predict'
      fullPath: '/predict'
      preLoaderRoute: typeof AuthenticatedPredictRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/positions': {
      id: '/_authenticated/positions'
      path: '/positions'
      fullPath: '/positions'
      preLoaderRoute: typeof AuthenticatedPositionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/forex': {
      id: '/_authenticated/forex'
      path: '/forex'
      fullPath: '/forex'
      preLoaderRoute: typeof AuthenticatedForexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crypto': {
      id: '/_authenticated/crypto'
      path: '/crypto'
      fullPath: '/crypto'
      preLoaderRoute: typeof AuthenticatedCryptoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bot-builder': {
      id: '/_authenticated/bot-builder'
      path: '/bot-builder'
      fullPath: '/bot-builder'
      preLoaderRoute: typeof AuthenticatedBotBuilderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/binary': {
      id: '/_authenticated/binary'
      path: '/binary'
      fullPath: '/binary'
      preLoaderRoute: typeof AuthenticatedBinaryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/aviator': {
      id: '/_authenticated/aviator'
      path: '/aviator'
      fullPath: '/aviator'
      preLoaderRoute: typeof AuthenticatedAviatorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps': {
      id: '/_authenticated/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AuthenticatedAppsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/daraja/stk-callback': {
      id: '/api/daraja/stk-callback'
      path: '/api/daraja/stk-callback'
      fullPath: '/api/daraja/stk-callback'
      preLoaderRoute: typeof ApiDarajaStkCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/daraja/b2c-timeout': {
      id: '/api/daraja/b2c-timeout'
      path: '/api/daraja/b2c-timeout'
      fullPath: '/api/daraja/b2c-timeout'
      preLoaderRoute: typeof ApiDarajaB2cTimeoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/daraja/b2c-result': {
      id: '/api/daraja/b2c-result'
      path: '/api/daraja/b2c-result'
      fullPath: '/api/daraja/b2c-result'
      preLoaderRoute: typeof ApiDarajaB2cResultRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAppsRoute: typeof AuthenticatedAppsRoute
  AuthenticatedAviatorRoute: typeof AuthenticatedAviatorRoute
  AuthenticatedBinaryRoute: typeof AuthenticatedBinaryRoute
  AuthenticatedBotBuilderRoute: typeof AuthenticatedBotBuilderRoute
  AuthenticatedCryptoRoute: typeof AuthenticatedCryptoRoute
  AuthenticatedForexRoute: typeof AuthenticatedForexRoute
  AuthenticatedPositionsRoute: typeof AuthenticatedPositionsRoute
  AuthenticatedPredictRoute: typeof AuthenticatedPredictRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedScannerRoute: typeof AuthenticatedScannerRoute
  AuthenticatedTradeRoute: typeof AuthenticatedTradeRoute
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAppsRoute: AuthenticatedAppsRoute,
  AuthenticatedAviatorRoute: AuthenticatedAviatorRoute,
  AuthenticatedBinaryRoute: AuthenticatedBinaryRoute,
  AuthenticatedBotBuilderRoute: AuthenticatedBotBuilderRoute,
  AuthenticatedCryptoRoute: AuthenticatedCryptoRoute,
  AuthenticatedForexRoute: AuthenticatedForexRoute,
  AuthenticatedPositionsRoute: AuthenticatedPositionsRoute,
  AuthenticatedPredictRoute: AuthenticatedPredictRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedScannerRoute: AuthenticatedScannerRoute,
  AuthenticatedTradeRoute: AuthenticatedTradeRoute,
  AuthenticatedWalletRoute: AuthenticatedWalletRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminSetupRoute: AdminSetupRoute,
  AuthRoute: AuthRoute,
  ApiDarajaB2cResultRoute: ApiDarajaB2cResultRoute,
  ApiDarajaB2cTimeoutRoute: ApiDarajaB2cTimeoutRoute,
  ApiDarajaStkCallbackRoute: ApiDarajaStkCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
